### ISSUE TITLE
Create initial version of module

### ISSUE THREAD

**Issue by rich-ehrhardt** [cloud-native-toolkit/terraform-azure-vpn-server#1]

**Comment by hemang-ibm** [comment]
@rich-ehrhardt 

we have created terraform module  "open vpn server"  by creating  azure linux vm with "open vpn ssl server" market place image. But right now we have not re-used existing vm module as suggested by you the reason being is in our existing linux vm module, we need to set one extra parameter "plan" as below, which is right now not part of our existing vm module. 

plan {
    name      = var.openvpn_image_sku
    product   = var.openvpn_image_offer
    publisher = var.openvpn_image_publisher
  }

If we want re-using existing vm module then we need to update this module to accommodate above plan parameter.

this module test case is passed. Please verify this approach and let us know your thoughts.

**Comment by hemang-ibm** [comment]
@rich-ehrhardt 

We have implemented below changes in this module:
1) Existing vm module reuse to create open-vpn-server module. (ubuntu 18.x/20.x supported)
2) boot strap script(custom data)  re-written to install open-vpn server and configure into vm.
3) script file created to download client.ovpn file and check vpn connection through cmd line open vpn client.
4) Integrated this script file to execute post module creation.(local-exec)

Please review.
